name: Go CI

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Go
              uses: actions/setup-go@v2
              with:
                  go-version: 1.17

            - name: Initialize Go module
              run: go mod init github.com/r3vv1l/coraline

            - name: Build
              run: go build -o main .
